[package]
name = "visto"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
libc = "^0.2"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"

[profile.release]
lto = true
strip = true
